# Generated by Django 5.0.2 on 2024-04-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_team_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
