# Generated by Django 5.0.3 on 2024-04-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('envapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envapp.environment'),
        ),
    ]
