# Generated by Django 5.0.3 on 2024-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoSource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
