# Generated by Django 5.0.2 on 2024-04-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoSource', '0009_admin_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_superadmin',
        ),
    ]
