# Generated by Django 5.0.2 on 2024-04-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoSource', '0010_remove_admin_is_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
