# Generated by Django 5.0.2 on 2024-04-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoSource', '0012_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
